# Generated by Django 4.0.6 on 2022-07-18 06:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0002_todoitem_owner_alter_todoitem_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoItem',
            new_name='Task',
        ),
    ]
