# Generated by Django 4.0.6 on 2022-07-18 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0003_rename_todoitem_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='ToDoItem',
        ),
    ]
