# Generated by Django 4.0.6 on 2022-07-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_profile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static\x07ccount_app\\images\\default-avatar.png', upload_to='media/images/avatars'),
        ),
    ]
