# Generated by Django 4.0.6 on 2022-07-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/images/default-avatar.png', null=True, upload_to='media/images/avatars'),
        ),
    ]
