# Generated by Django 4.0.6 on 2022-07-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=110, null=True, unique=True),
        ),
    ]
